exp:
  config_dir: configs
  config: td_single_cat.yaml
  project: TestRefactor
  tags:
    - after demodulation
  name: cat_offsets_l2
  seed: 12
  root: .
  notes: empty notes
  logging: true
  step_save: 100
  trainer: td_single
training:
  iter_num: 400
  batch_size: 8
  device: cuda:0
  generator: stylegan2
  phase: mapping
  patch_key: cin_mult
  source_class: Cat
  target_class: Lion
  auto_layer_k: 16
  auto_layer_iters: 0
  auto_layer_batch: 8
  mixing_noise: 0.9
optimization_setup:
  visual_encoders: 
    - ViT-B/32
    - ViT-B/16
  loss_funcs:
    - direction
    - offsets_l2
  loss_coefs:
    - 1.0
    - 0.5
  g_reg_every: 4
  optimizer:
    weight_decay: 0.0
    lr: 0.02
    betas:
    - 0.9
    - 0.999
generator_args:
  checkpoint_path: pretrained/StyleGAN2/stylegan2-cat-config-f.pt
  img_size: 256
evaluation:
  is_on: false
  vision_models:
    - ViT-B/32
    - ViT-L/14
  step: 100000
  data_size: 500
  batch_size: 24
logging:
  log_every: 10
  log_images: 20
  latents_to_edit: []
  truncation: 0.5
  num_grid_outputs: 1
checkpointing:
  is_on: false
  start_from: false
  step_backup: 100000